### ISSUE TITLE
Can't install: add-on appears to be corrupt

### ISSUE THREAD

**Issue by gka** [sammacbeth/dat-fox#19]
![screenshot at 2018-06-05 18-43-02](https://user-images.githubusercontent.com/617518/40990231-708bbda8-68f0-11e8-893b-0248143820fb.png)

Firefox Quantum 58.0.1 (64-bit) on Debian/Linux

**Comment by sammacbeth** [comment]
Thanks for reporting. Is this the version in the Mozilla addon store, or the release on Github? I wasn't able to reproduce this when re-installing the extension in my system.

**Comment by gka** [comment]
it was the version from the addon store

**Comment by sammacbeth** [comment]
Does this issue persist? Usually this error is tied to a signing error with the addon xpi. As this is all handled by Mozilla on the addon store, then there may be problem on their end, or your Firefox install is not able to verify the store's signing key.

**Comment by gka** [comment]
just tried it again, and I still get the same error message. is there a way to see a log of what went wrong during addon install?

**Comment by gka** [comment]
tried it on a different machine (Ubuntu-based instead of Debian), and it worked fine. Maybe there's an issue with Debian?
