### ISSUE TITLE
Replace dat.redirect domain

### ISSUE THREAD

**Issue by evilpie** [sammacbeth/dat-fox#3]
Please instead of using `dat.redirect` use a [Reserved domain](https://en.wikipedia.org/wiki/Top-level_domain#Reserved_domains). In the unlikely case that something goes wrong with the extension, nobody could every register `.redirect`. For example `dat.redirect.localhost` would work.

**Comment by sammacbeth** [comment]
This is a good point, I'll update it. `dat.localhost` is nice because it also conveys that the bridge is running locally when the protocol handler popup is displayed.
