### ISSUE TITLE
Support the new Firefox decentralized features

### ISSUE THREAD

**Issue by DaniellMesquita** [sammacbeth/dat-fox#31]
I've hear that from Firefox 57 there would have support for extensions with decentralized protocols (really enabling dat:// protocol and others).
I think this extension should update to this.

**Comment by sammacbeth** [comment]
This is exactly what this extension does. The support you mention was for support for protocols such as `dat` with the [`protocol_handler` manifest key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers).

**Comment by DaniellMesquita** [comment]
@sammacbeth
But it says the extension can't show "dat://" protocol on addressbar, so how Firefox supports the protocol?

**Comment by sammacbeth** [comment]
Yes, the support for protocols that was [announced](https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/) is just that the browser will accept a url starting with `dat://`, however the limitations of the API mean that we can only do a redirect from these urls.

If you are looking for full `dat://` protocol support in Firefox, check out the [libdweb](https://github.com/mozilla/libdweb) project. Using this I have an experimental extension running proving dat protocol support: https://github.com/cliqz-oss/dat-webext
