### ISSUE TITLE
Unable to start the gateway : resetBridge is not a function.

### ISSUE THREAD

**Issue by N07070** [sammacbeth/dat-fox#32]
Hello, 

Today I tried out the 0.2.0 version of the extension, downloaded from github, as it is more recent than the one on the Firefox Add-ons Store. The previous version did not work either, but didn't give any indication as to why.

With this extension, however, when I open the setup page and attempt to check the helper connexion, this error occures :  

```
Checking helper connection
Attempting to start gateway... TypeError: resetBridge is not a function
```

I installed the dat-fox-helper from github, with the script provided in the README, that I read and understood before executing it.

I'm running a Debian 9, with Firefox 60.3.0esr (64-bit).

Thanks for your work, I hope you can fix this issue soon.

**Comment by sammacbeth** [comment]
That version is an experimental version using APIs from [libdweb](https://github.com/mozilla/libdweb) and is far from stable. I recommend sticking to the addon store version, or the master branch of this repo.
