### ISSUE TITLE
0x65.dev blog loads up until Dec 4th only

### ISSUE THREAD

**Issue by da2x** [sammacbeth/dat-fox#41]
1. open http://ee172d7cd9235b2cf86ea9481e8a40e48cea29c743036621edc79a4765aa0281/ in Firefox

Front page stops at Dec 4th.

1. open dat://ee172d7cd9235b2cf86ea9481e8a40e48cea29c743036621edc79a4765aa0281/ in Beaker

Front page updates through Dec 22

**Comment by sammacbeth** [comment]
Looks like you're dat-fox-helper is stuck on an older version of the site and not updating. Which version of the helper are you using? I recently published a new version that should have much better performance and reliability.

**Comment by da2x** [comment]
I’m using v0.2.1 on Fedora Linux 31. I installed it yesterday using the method the extension suggestions. Other Dat-sites appear to work fine.

**Comment by sammacbeth** [comment]
Does this issue persist? I may be that peers were down preventing you from getting an up-to-date version. If not, you could try deleting the data in your library directory (`~/.local/datfox/library/dat2/ee17...`).

**Comment by da2x** [comment]
> Does this issue persist?

Yes, on a Linux system and on a macOS system.

> […] your library directory `~/.local/datfox/library/dat2/[…]`

Mine was located in `dat1`. When is dat2 shipping, anyway?

> deleting the data in your library

That resolved the issue. I deleted it on both my systems without making a backup. That was probably stupid. Not sure how to help you debug this without those directories.

**Comment by sammacbeth** [comment]
> > […] your library directory `~/.local/datfox/library/dat2/[…]`
> 
> Mine was located in `dat1`. When is dat2 shipping, anyway?

Sorry, `dat1` is correct. Experimental dat2 support is working, but still have to implement backwards-compatibility.

It sounds like maybe the data on disk got corrupted, preventing an update to latest version of the archive. Maybe a hyperdrive issue. I'll close this issue for the time being, but keep in mind that these kind of errors can occur.
